swagger: "2.0"
info:
  description: "This is a  node js test application"
  version: "1.0.0"
  title: "node test"

basePath: "/v1"

tags:

- name: "humans"
  description: "user be humans in this pattern"



- name: "pets"
  description: "Operations about pets of humans"


schemes:
- "https"
- "http"


paths:

  /humans:

    get:
      tags:
      - "Human"
      summary: "list all humans"
      description: ""
      operationId: "listComplex"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        400:
          description: "Invalid ID supplied"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Human"



  /humans/{name}/pets:

    get:
      tags:
      - "Complex"
      summary: "Finds pets by humans name"
      description: "return object of humans pets"
      operationId: "findPetsByHumansName"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "name of humans"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
        400:
          description: "Invalid status value"




definitions:


  Human:
    type: "object"
    required:
    - "name"
    - "age"
    - "ownerId"

    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "flat no"
      age:
        type: "integer"
      privatePetsStatus:
        type: "string"
        enum: ["active"]
      pets:
        $ref: "#/definitions/Pet"






  Pet:
    type: "object"

    required:
    - "name"
    - "type"
    - "ownerId"

    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      type:
        type: "string"
      ownerId:
        type: "integer"
        format: "int32"
        description: "humans id"
    
